#!/bin/bash
VARIANTS=(CLHT ABSL ABSL_LINEAR_REHASH_CLUSTER_DEAMORTIZED ICEBERG_SINGLE_THREAD CLHT CUCKOO GRHM TRHM RHM GZHM_ADAPTIVE)
UPDATE_PCTS=(50)
LOAD_FACTORS=(95)
THROUGHPUT_FREQ=1
CHURN_CYCLES=50

for UPDATE_PCT in ${UPDATE_PCTS[@]}; do
for LOAD_FACTOR in ${LOAD_FACTORS[@]}; do
for VARIANT in ${VARIANTS[@]}; do

echo "./bench/paper_final/churn.sh latency ${VARIANT} ${LOAD_FACTOR} ${UPDATE_PCT} ${THROUGHPUT_FREQ}"
time ./bench/paper_final/churn.sh latency ${VARIANT} ${LOAD_FACTOR} ${UPDATE_PCT} ${THROUGHPUT_FREQ} ${CHURN_CYCLES}
done
done
done

exit 0
